#!/bin/bash

if [[ $# == 0 ]]; then
    echo usage: $0 'raspbian-package [raspbian-packages...]'
    exit 1
fi

export DEBIAN_FRONTEND=noninteractive
ARCH=armhf

apt-get update
for deb in "$@"; do
    apt-get download $deb:$ARCH
    dpkg-deb -x ${deb}_*_$ARCH.deb $RASPBIAN_ROOT
done

/rpxc/fix-symlinks $RASPBIAN_ROOT
