#!/bin/bash

if [[ $# == 0 ]]; then
    echo usage: $0 '<raspberry-pi-package(s)>'
    exit 1
fi

export DEBIAN_FRONTEND=noninteractive
ARCH=armhf

for deb in "$@"; do
    apt-get download $deb:$ARCH
    dpkg -f ${deb}_*_$ARCH.deb Depends
    dpkg-deb -x ${deb}_*_$ARCH.deb $CCROOT
done

/rpxc/fix-symlinks $CCROOT
