#!/usr/bin/env perl

use 5.14.0;
use warnings;

use File::Find qw(find);

my $root = $ARGV[0]
    or die "usage: $0 <root-dir>\n";
my $errors = 0;

my $opts = {
    wanted => \&file_cb,
};
find($opts, $root);
exit($errors == 0 ? 0 : 1);

sub file_cb {
    my $link = $_;
    return unless -l $link;
    my $dest = readlink $link;
    return if -e $dest;

    my $newdest = $root . $dest;
    if (-e $newdest) {
        unlink $link;
        symlink($newdest, $link);
#        say "New link: ", readlink($link);
    }
    else {
        warn "Missing file -> $dest\n";
        $errors++;
    }
}
